version: '3'
services:
  auth-api:
    image: jamescalleja/auth-api:latest
    networks:
      - owapp
    ports:
      - "5000:5000"
  ocr-worker:
    image: jamescalleja/ocr-worker:latest
    networks:
      - owapp
    depends_on:
      - auth-api
  order-api:
    image: jamescalleja/order-api:latest
    networks:
      - owapp
    depends_on:
      - auth-api
      - ocr-worker
  redis-queue:
    image: redis
    ports:
      - "63790:6379"
    networks:
      - owapp
networks:
  owapp:
    driver: bridge