version: '3'
services:
  auth-api:
    image: jamescalleja/auth-api:latest
    networks:
      - webapp
    ports:
      - "5000:5000"
  ocr-worker:
    image: jamescalleja/ocr-worker:latest
    networks:
      - webapp
    ports:
      - "6379:6379"
    depends_on:
      - auth-api
  order-api:
    image: jamescalleja/order-api:latest
    ports:
      - "5500:5000"
      - "63790:6379"
    networks:
      - webapp
    depends_on:
      - auth-api
      - ocr-worker
networks:
  webapp:
    driver: bridge