version: '3'
services:
  auth-api:
    image: jamescalleja/auth-api:latest
    networks:
      - owapp
  ocr-worker:
    image: jamescalleja/ocr-worker:latest
    networks:
      - owapp
    depends_on:
      - auth-api
      - redis-queue
  order-api:
    image: jamescalleja/order-api:latest
    networks:
      - owapp
    depends_on:
      - auth-api
      - ocr-worker
  redis-queue:
    image: redis
    networks:
      - owapp
  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    command:
      - /bin/sh
      - -c
      - |
        whoami
        cat  /usr/local/etc/haproxy/haproxy.cfg
        haproxy -v 
        haproxy  -f /usr/local/etc/haproxy/haproxy.cfg -p /run/haproxy.pid -db
    networks:
      - owapp
    depends_on:
      - auth-api
      - ocr-worker
      - order-api
networks:
  owapp:
    driver: bridge